### ISSUE TITLE
feat(architecture): improve project structure

### ISSUE THREAD

**Issue by ronz204** [rruiz204/pets-and-paws-api#3]
### Tasks

- [x] Create forgot password endpoint
- [x] Create reset password endpoint
- [x] Configure CORS
- [x] Configure Rate Limiting
- [x] Create Response Formatter Filter
- [x] Seed Roles
- [x] Create ER Diagram
- [x] Configure Policies and Authorization
- [x] Improve Bootstrap file structure
